### ISSUE TITLE
Process completed with exit code 7.

### ISSUE THREAD

**Issue by liemlylac** [peter-evans/docker-compose-actions-workflow#2]
Nice example, but when running in my action, it failed.

Action Logs:
```properties
Run docker run --rm appropriate/curl -s --retry 3 --retry-connrefused http://localhost:8080/
Unable to find image 'appropriate/curl:latest' locally
latest: Pulling from appropriate/curl
ff3a5c916c92: Pulling fs layer
3151abf94102: Pulling fs layer
58ae3cb4aac4: Pulling fs layer
3151abf94102: Verifying Checksum
3151abf94102: Download complete
58ae3cb4aac4: Verifying Checksum
58ae3cb4aac4: Download complete
ff3a5c916c92: Download complete
ff3a5c916c92: Pull complete
3151abf94102: Pull complete
58ae3cb4aac4: Pull complete
Digest: sha256:c8bf5bbec6397465a247c2bb3e589bb77e4f62ff88a027175ecb2d9e4f12c9d7
Status: Downloaded newer image for appropriate/curl:latest
##[error]Process completed with exit code 7.
```

My docker-compose file:

```yml
version: '3.7'

services:
  wordpress:
    image: wordpress:latest
    depends_on:
      - wordpress_db
    ports:
      - "8080:80"
#    volumes:
#     - type: bind
#       source: ./wp-content
#       target: /var/www/html/wp-content
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress

  wordpress_db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - wordpress_db
    restart: always
    ports:
      - "8888:80"
    environment:
      PMA_HOST: wordpress_db
      MYSQL_ROOT_PASSWORDL: secret
    networks:
      - back

networks:
  back:
volumes:
  db_data: {}
```

My action workflow file:

```yml
name: build
on: 
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build services
        run: docker-compose up -d
      - name: List container
        run: docker-compose ps
      - name: Test Wordpress container
        run: docker run --rm --network container:wordpress-docker-compose_wordpress_1 appropriate/curl -s --retry 3 --retry-connrefused http://localhost:8080/
      - name: Test PhpMyAdmin container
        run: docker run --rm --network container:wordpress-docker-compose_phpmyadmin_1 appropriate/curl -s --retry 3 --retry-connrefused http://localhost:8888/

```
